FROM python:3.8.10

ENV PYTHONBUFFERED 1
COPY ./requirements.txt /requirements.txt

RUN pip3 install --user -U nltk
RUN pip3 install -U pip setuptools
RUN pip3 install -U -r /requirements.txt

RUN mkdir /scraper
COPY ./scraper /scraper
RUN chmod 755 /scraper/Models/final_model_pytorch
RUN chmod 755 /scraper/Models/saved_model

WORKDIR /scraper
