services:
    product:
        build:
          context: ./
          dockerfile: dockerfile-product.yaml
        restart: always
        ports:
          - "1323:1323"
        environment:
          DB_USER: wronglyaroundromance
          DB_PASSWORD: xaumGvWmWNJtMhAOtmfR9ZtqdBj
          DB_HOST: postgre:5432
          DB_NAME: human_db
          TWILIO_USERNAME: AC7ed880bbbac683e5c3ff3b553631be20
          TWILIO_PASSWORD: a7777e98e72f5741c4c5da832f81807b
          PYTHON_HOST: app
        depends_on:
          - app
          - postgre

    selenium:
        image: selenium/standalone-chrome
        ports:
        - 4444:4444
        restart: always

    app:
        build:
          context: .
          dockerfile: dockerfile-python.yaml
        command: sh -c "python3 oddsportal_scraper.py"
        ports:
          - "5000:5000"
        restart: always
        depends_on:
        - selenium 

    postgre:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
          - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: wronglyaroundromance
            POSTGRES_PASSWORD: xaumGvWmWNJtMhAOtmfR9ZtqdBj
            POSTGRES_DB:  human_db
volumes:
  db_data:

  