FROM python:3.8.10

ENV PYTHONBUFFERED 1
COPY ./requirements.txt /requirements.txt

RUN apt-get update && apt-get install -y \
    wget \
    unzip 

RUN pip install --no-cache-dir gdown

RUN pip3 install --user -U nltk

RUN pip3 install -U pip setuptools

RUN pip3 install -U -r /requirements.txt

RUN pip3 install gdown

RUN mkdir /scraper

RUN gdown --id 1SHsAEG1Vo7XUwB5_zW9UREwuEGav91qp --output downloaded_file.zip && \
    unzip downloaded_file.zip -d ./scraper/Models/ && \
    rm downloaded_file.zip

COPY ./scraper /scraper
WORKDIR /scraper
